# Generated by Django 4.0.6 on 2022-07-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shakn', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
